<a href="https://colab.research.google.com/github/puttarajkoliwad/python_beginner/blob/master/Copy_of_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Data types

###01) str
'str' is the standard string type class in python

- str concatenation '+' operator works b/w two 'str' instances only.

In [20]:
name = "iPhone 5s"
type(name)
print(name)

iPhone 5s


###02) float

In [21]:
screen_size = 4.3
type(screen_size)
print("screen_size: {}".format(screen_size))

screen_size: 4.3


###03) int
for integer values

In [22]:
no_speakers = 3
print(type(no_speakers))
print("number of speakers: {}".format(no_speakers))
print(name + " has " + str(no_speakers) + " speakers.")

<class 'int'>
number of speakers: 3
iPhone 5s has 3 speakers.


In [23]:
a = 3
b = 2
print(a+b, a-b, a/b, a//b, a*b, a**b, a%b)

5 1 1.5 1 6 9 1


###04) bool
for Boolean values

In [24]:
is_android = False
print(type(is_android))
print("is Android? " + str(is_android))
print(is_android == False and no_speakers > 1)

<class 'bool'>
is Android? False
True


###05) None:
`None` datatype is used to define **nil/null/undefined** data in python3
    
    Eg.: a = None

#Python Blocks(:)
  - python blocks strictly follow indentation to identify start and end of a block. 
  - The beginning of a block is denoted by appending *colon(":")* at the end of starting statement.

###01) Conditional statements:
- if-else blocks:

In [25]:
if not is_android:
  print(name + " supports Android")
elif False:
  print("This is how we write elsif")
else:
  print(name + " doesn't support Android")

condition = "if"
if condition == "if":
  print("'if' block")
elif condition == "elif":
  print("'elif' block")
else:
  print("'else' block")

iPhone 5s supports Android
'if' block


- match-case blocks: These are the 'switch/when' parallels in python. (python3.10+)

In [26]:
# case_stmt = "stmt1"
# match case_stmt:
#   case "stmt1":
#     print("case 1")
#   case "stmt2":
#     print("case 2")
#   case _:
#     print("default case")

###02) Python loops
- for loop: the looping variable is **immutable** in for loop, just like in ruby

In [27]:
for i in range(5):
  print(i, i**2)
  if i == 2:
    i += 3
    print("i: " + str(i))

0 0
1 1
2 4
i: 5
3 9
4 16


- while loop

In [28]:
i = 0
while(i < 5):
  print(i, i**2)
  if(i==2):
    i += 3
  i += 1

0 0
1 1
2 4


# Function Definition in Python
- A function definition starts with **'def'** key word in python, and follows the same rules that apply to every other block for parsing.
- the function call should be initiated seperately when needed unlike javascript self-invoking functions.
- the returning values of the function should be explicitly specified using ***'return'*** keyword.
- **optional** parameters of the function should be assigned the **default** values in the function definition using the **'='** operator.
- ***function-hints*** can be provided to each function by using 3 double quotes(**" " "** *hint text* **" " "**)

In [29]:
def my_function():
  print("inside my_function block")
my_function()

def area_of_rectangle(len, wid = None):
  """This is the hint text for the function and can be written anywhere inside the function block"""
  if not wid:
    return len * len
  return len * wid
my_area = area_of_rectangle(3, 4)
my_square_area = area_of_rectangle(5)
print(my_area)
print(my_square_area)
area_of_rectangle?

inside my_function block
12
25


# Advanced Data Structures in Python
###01) Lists (list)
    - Lists are heterogenic collection of objects, with variable size
    - similar to Arrays in Javascript, Ruby and ArrayLists in Java

In [30]:
my_list = [name, screen_size, no_speakers, is_android]
print(type(my_list))
my_list2 = my_list[:] # speard operator
my_list2.append("appended element") # appending values to the list
list3 = my_list + my_list2 # concatenation of lists
print(my_list)
print(my_list2)
print(list3)
print(list3[2:4]) # accessing a range of list elements, exclusive of range outer bound(4 here)
print()
# Iterating over lists
print(("=" * 6) + " Iterating over lists" + ("=" * 6))
for element in my_list:
  print(element)

<class 'list'>
['iPhone 5s', 4.3, 3, False]
['iPhone 5s', 4.3, 3, False, 'appended element']
['iPhone 5s', 4.3, 3, False, 'iPhone 5s', 4.3, 3, False, 'appended element']
[3, False]

====== Iterating over lists======
iPhone 5s
4.3
3
False


- **map**: 'map' function takes a lambda function and a list and performs lambda operation on each element of the list and stores the result as a **map** object. 
      map(lambda, list)

In [31]:
lam = lambda x: x**2
print(lam(2))

a = list(range(5))
map_result = map(lam, a)
print(map_result)
print(list(map_result))

4
[0, 1, 4, 9, 16]


- **filter**: 'filter' function is used to select required elements of the list.
  - It takes a lambda function and a list and filters list elements based on lambda selection.
  - It stores the result into **filter** object.
        filter(lambda, list)
      

In [32]:
filter_result = filter(lambda x: x%2 == 0, a)
print(filter_result)
print(list(filter_result))

[0, 2, 4]


###02) Tuples
Tuples are the 'immutable' lists. Once initiated their values can **NOT** be changed. Elsewise they are very much similar to lists.
- Tuples are comparative faster compared to lists since they are immutable.
- **tuple** elements are enclosed within 'parenthesis'

In [33]:
tuple1 = (name, screen_size, is_android)
type(tuple1)
print(tuple1)
tuple1[2]
# tuple1[2] = True # error here. Tuple doesnt support assignment operation!
tuple2 = tuple(list3)
print(tuple2)

# traversing
for data in tuple1:
  print(data)

('iPhone 5s', 4.3, False)
('iPhone 5s', 4.3, 3, False, 'iPhone 5s', 4.3, 3, False, 'appended element')
iPhone 5s
4.3
False


In [34]:
# proof that tuples are faster than lists
import time
squares = lambda x: x**2

list1 = list(range(1000000))
l0 = time.time()
map(squares, list1)
l1 = time.time()
print("lists time:", (l1 - l0))

tuple1 = tuple(range(1000000))
t0 = time.time()
map(squares, tuple1)
t1 = time.time()
print("tuples time:", (t1 - t0))

lists time: 9.226799011230469e-05
tuples time: 9.5367431640625e-05


###03) Sets (set)
Sets are collection of unique elements. Sets **DO NOT** support dynamic access just like in java.
- Sets are enclosed within 'curly braces{}'
- new(), add(elem), update(another_set), remove(elem) are few CRUD methods of sets
- sets are comparatively faster than lists when trying to check presence of an element in it.

In [35]:
set1 = set(my_list)
set1.add(4.3) #append element to the set
set2 = {"new2"}
set1.add("new element")
print(set1)
set1.update(set2) # concatenates two sets, mutates the original set.
print(set1)
set1.remove("new2") # removes element from the set
print(set1)

t0 = time.time()
print(87 in list1)
print(898987 in list1)
print(8987987987 in list1)
t1 = time.time()
print("lists: ", (t1 - t0))

set1 = set(range(1000000))
st0 = time.time()
print(87 in set1)
print(898987 in set1)
print(8987987987 in set1)
st1 = time.time()
print("sets: ", (st1 - st0))

{False, 3, 4.3, 'new element', 'iPhone 5s'}
{False, 3, 4.3, 'new element', 'iPhone 5s', 'new2'}
{False, 3, 4.3, 'new element', 'iPhone 5s'}
True
True
False
lists:  0.052907705307006836
True
True
False
sets:  0.0020868778228759766


###04) Dictionaries (dict):
Dicts are key-value paired datatypes in python. Like Hash in ruby.

**`dict.keys(), dict.values(), dict.items()`** are a few major functions in dicts.

- can be initialized with empty braces `{}`
- entries can be accessed using `[]` with key names.
- Symbols are **NOT** allowed!


In [36]:
phone_details = {"size": "4.3", "color" : "black"}
phone_details["name"] = 'iPhone'
print(phone_details)
print(phone_details["name"])

{'size': '4.3', 'color': 'black', 'name': 'iPhone'}
iPhone


#Python Packages

- `import` keyword is used to import modules into other files.
- `import module_name`
- `import module_name as alias_name`
- `from module_name import function_name`

These are all valid usages of `import` keyword.

In [37]:
!echo 'def module_function(num=None):' > foreign_file.py
!echo "    return 'This is from other module'" >> foreign_file.py
!cat foreign_file.py
!ls

def module_function(num=None):
    return 'This is from other module'
foreign_file.py  __pycache__  sample_data


In [38]:
import math
print(math.sqrt(4))

import foreign_file as ff
print(ff.module_function(4))

2.0
This is from other module


# File Handling in Python:
####01) open():
`open(file_path, operation_mode)` will open the file in specified `operation_mode` and allows us to perform file operations.

`f1 = open('my_csv.csv', 'r')`

####02) file.readline():
`f1.readline()` will read one line from the buffer.

####03) file.read():
`f1.read()` read all the content of file in one go.

####04) file.write('data'):
`f1.write('data')` will allow us to write data to a file when the file is opened in **'w'** mode. It **won't** write to new line by default. It will just continue in the same line.

####05) file.close():
`f1.close()` will close the file after which no read/write can be performed on that file.

In [39]:
!wget https://media.githubusercontent.com/media/datablist/sample-csv-files/main/files/organizations/organizations-100.csv -o 'organizations.csv'

In [40]:
f1 = open('organizations-100.csv', 'r')
s = f1.readline()
print(s.split(","))
full_text = f1.read()
f1.close()

with open('new_file.txt', 'w') as file:
  file.write("This is a new line. ")
  file.write("This will continue in the same line...\n")
  # file.append("Trying to add new line directly") #error here

!cat new_file.txt

with open('organizations-100.csv', 'r') as file:
  for line in file:
    for word in line.split(","):
      print(word)
      break

['Index', 'Organization Id', 'Name', 'Website', 'Country', 'Description', 'Founded', 'Industry', 'Number of employees\n']
This is a new line. This will continue in the same line...
Index
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


#OOPs in Python:
##01) Classes in Python:
- `class` keyword is used to create classes in python
- CamelCase is followed for python classes.
- `__init__(self, params):` is used as the constructor method/initializer.
- `__str(self)__:` is like toString() of java which should return a string.
- **NO** need of `new` keyword. You could just invoke class name with params just like any other function call and it will create an instance of that class. 

  `my_instance = MyClass(positional_arg)`
- just like in Javascript, we can assign **dynamic properties** for instances of objects in python3 also.

  `my_instance.some_random_property = "some_random_value"`
  `print(my_instance.some_random_property) #=> "some_random_value"`

In [41]:
class BasePhone:
  """This is a sample phone class..."""
  def __init__(self, name, is_android = True, screen_size = 4.3):
    self.name = name
    self.is_android = is_android
    self.screen_size = screen_size

  def __str__(self):
    return self.name + " " + str(self.is_android) + " " + str(self.screen_size)

my_phone = BasePhone("Honor",True,5.2)
print(type(my_phone))
print(my_phone.__doc__)
print(my_phone)

<class '__main__.BasePhone'>
This is a sample phone class...
Honor True 5.2


##02) Inheritance:
Syntactically inheritance in python is achieved in following manner `class ChildClass(ParentClass):`.

In [44]:
class IPhone(BasePhone):
  """This is for iPhones and this class extends BasePhone"""
  def __init__(self, name):
    BasePhone.__init__(self, name, False, 4)

my_iphone = IPhone("Apple14")
my_iphone.random_prop = "random value" #works perfectly fine
print(type(my_iphone))
print(my_iphone.__doc__)
print(my_iphone)
print(my_iphone.random_prop)


<class '__main__.IPhone'>
This is for iPhones and this class extends BasePhone
Apple14 False 4
random value


# NumPy: https://numpy.org/doc/stable/reference/index.html#reference
- `NumPy` stands for NumericalsPy. This library as the name suggests a bundle of Numerical functions that make the study of **deep-learning** much easier.

  `import numpy as np` is a common way of importing NumPy.


In [39]:
# https://numpy.org/doc/stable/reference/index.html#reference
import numpy as np

X = np.array([1, 2, 3]) #arrays of np are ndarray meaning n-dimension-array
print(X)
Y = np.array([1, 2, 3], float) # converts the array elements to float types
print(Y)
print(type(X))
print(X.shape) # prints the dimensions of the array as tuple (3,) in this case
X = np.random.random((3,4))
Y = X.T # Transpose the matrix (2D array here)
print(X)
print(Y)
print(Y[1, 0:2]) # for [i, j:k] returns i'th row from 'j' to 'k'. 'j' inclusive, 'k' exclusive
Y1 = Y.reshape(6, 2) # ndarray.reshape(rows, columns) reshape the matrix into given rows and columns. throws error if new rows*columns exceeds previous number of cells
print(Y1)
Z = np.eye(3, 3, 0, int) # creates an identity matrix of (M*N*K). The datatype will be float by default.
print(Z)
X = np.ones((3, 4), int) # creates a matrix of M*N with all 1s. Use np.zeros for matrix of 0s.
print(X)

A = np.arange(5) # creates an array till range of 0-5. 5 excluded.
B = np.arange(5)

print(A+B) # point wise addition
print(A-B) # point wise substraction
print(A*B) # point wise multiplication. This is NOT same as matrix multiplication.

print("scalar broadcasting(A+1):", A, "=>", A+1) # A + 1, broadcasting +1 to all the elements of A. Here A is considered a vector entity and 1 is a scalar entity.

X = np.floor(np.random.random((3, 4))*10)
print(X)


# Vector multiplications.
u = [1, 2, 3]
v = [-1, 0, 1]

# 01) Inner product
inn = np.inner(u,v) # point wise multiply u and v and then sum it up.
print(inn)

# 02) Outer product
outr = np.outer(u,v)
print(outr)

# 03) Dot product. Yields actual matrix multiplication with all applicable rules of it.
A = np.ones((2, 3))
B = np.ones((3,2))
print(A)
print(B)
dott = np.dot(A,B)
print(dott)
print(np.dot(A.T, B.T)) # A * B = B` * A`

print(A.sum()) # prints sum of all the elements of A
print(A.sum(axis = 0)) # prints sum of elements of each column
print(A.sum(axis = 1)) # prints sum of elements of each row

[1 2 3]
[1. 2. 3.]
<class 'numpy.ndarray'>
(3,)
[[0.64923138 0.77001287 0.45651248 0.19967168]
 [0.83430386 0.12183967 0.32822073 0.68866362]
 [0.17387201 0.77796242 0.59147888 0.19417124]]
[[0.64923138 0.83430386 0.17387201]
 [0.77001287 0.12183967 0.77796242]
 [0.45651248 0.32822073 0.59147888]
 [0.19967168 0.68866362 0.19417124]]
[0.77001287 0.12183967]
[[0.64923138 0.83430386]
 [0.17387201 0.77001287]
 [0.12183967 0.77796242]
 [0.45651248 0.32822073]
 [0.59147888 0.19967168]
 [0.68866362 0.19417124]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[0 2 4 6 8]
[0 0 0 0 0]
[ 0  1  4  9 16]
scalar broadcasting(A+1): [0 1 2 3 4] => [1 2 3 4 5]
[[9. 0. 5. 9.]
 [8. 7. 2. 8.]
 [1. 5. 0. 1.]]
2
[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
6.0
[2. 2. 2.]
[3. 3.]
